#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-01-26 22:49:31
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

import os
from bs4 import BeautifulSoup
import requests
import json
import urllib.request, urllib.response


def getinfo(url='', category=''):
    record = []
    for i in range(1, 5):
        pageurl = url + r'&page={0}'.format(i)
        try:
            header = {'Host': 'www.vipmro.com',
                      'Connection': 'close',
                      'Upgrade-Insecure-Requests': '1',
                      'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'}
            response = requests.get(pageurl, timeout=8, headers=header, verify=False)
        except Exception as er:
            print(er)
            continue
            # raise Exception('出错，停止')
        soup = BeautifulSoup(response.content, 'lxml')
        items = soup.find_all('div', class_="list-main-box-cont")
        
        for item in items:
            title = item.find('a', target='_blank')['alt']  # 商品标题
            model_code = item.find('span', class_="model m-top5").text.split('：')[-1]+'\n'  # 商品型号
            # product_id =
            r = {'title': title,
                 'model': model_code,
                 }
            record.append(model_code)
    return record


if __name__ == '__main__':
    categorys = [
        {'categoryid': '501110', 'categoryname': '断路器'},
        {'categoryid': '501111', 'categoryname': '继电器'},
        {'categoryid': '501112', 'categoryname': '接触器'},
        {'categoryid': '501113', 'categoryname': '电涌保护器'},
        {'categoryid': '501114', 'categoryname': '熔断器'},
        {'categoryid': '501115', 'categoryname': '互感器'},
        {'categoryid': '501116', 'categoryname': '功率补偿器件'},
        {'categoryid': '501118', 'categoryname': '电动机控制器'},
        {'categoryid': '501119', 'categoryname': '电动机保护器'},
        {'categoryid': '501124', 'categoryname': '隔离开关'},
        {'categoryid': '501125', 'categoryname': '负荷开关'},
        {'categoryid': '501199', 'categoryname': '其他'},
        {'categoryid': '501127', 'categoryname': '双电源开关'},
        {'categoryid': '501210', 'categoryname': '按钮及指示灯'},
        {'categoryid': '501211', 'categoryname': '工业开关'},
        {'categoryid': '501213', 'categoryname': '控制开关'},
        {'categoryid': '501214', 'categoryname': '自动控制开关'},
        {'categoryid': '501215', 'categoryname': '电阻器'},
        {'categoryid': '501217', 'categoryname': '起动器'},
        {'categoryid': '501218', 'categoryname': '定时器'},
        {'categoryid': '501219', 'categoryname': '计数器'},
        {'categoryid': '501220', 'categoryname': '温控器'},
        {'categoryid': '501222', 'categoryname': '数字面板表'},
        {'categoryid': '501223', 'categoryname': '导轨元器件'},
        {'categoryid': '501224', 'categoryname': '电磁铁'},
        {'categoryid': '501299', 'categoryname': '其他'},
        {'categoryid': '501310', 'categoryname': '稳压器'},
        {'categoryid': '501311', 'categoryname': '调压器'},
        {'categoryid': '501312', 'categoryname': '变压器'},
        {'categoryid': '501313', 'categoryname': '逆变电源、充电机'},
        {'categoryid': '501314', 'categoryname': '通用开关电源'},
        {'categoryid': '501318', 'categoryname': '其他'},
        {'categoryid': '501018', 'categoryname': '配电箱、电气箱体'},
        {'categoryid': '501020', 'categoryname': '电能及测量仪表'},
        {'categoryid': '501017', 'categoryname': '工业连接器'},
        {'categoryid': '501016', 'categoryname': '排插、转换器'},
        {'categoryid': '501015', 'categoryname': '接线端子'},
        {'categoryid': '501011', 'categoryname': '扎线带'},
        {'categoryid': '501012', 'categoryname': '电线、电缆'},
        {'categoryid': '501013', 'categoryname': '电缆卷盘、卷管器、绕线器'},
        {'categoryid': '501014', 'categoryname': '线缆保护、线缆配件'},
        {'categoryid': '501010', 'categoryname': '电工胶带'},
        {'categoryid': '501019', 'categoryname': '电工配件'},
        {'categoryid': '501023', 'categoryname': '母排'},
        {'categoryid': '501024', 'categoryname': '绝缘子'},
        {'categoryid': '501099', 'categoryname': '其他'},
        {'categoryid': '502010', 'categoryname': '传感器'},
        {'categoryid': '502024', 'categoryname': '变频器'},
        {'categoryid': '502011', 'categoryname': '小型PLC'},
        {'categoryid': '502012', 'categoryname': '中、大型PLC'},
        {'categoryid': '502013', 'categoryname': 'PLC配件'},
        {'categoryid': '502016', 'categoryname': '运动控制'},
        {'categoryid': '502017', 'categoryname': '人机界面'},
        {'categoryid': '502019', 'categoryname': '工业安全'},
        {'categoryid': '502020', 'categoryname': '现场总线'},
        {'categoryid': '502021', 'categoryname': '以太网'},
        {'categoryid': '501410', 'categoryname': '手电筒、便携式照明灯'},
        {'categoryid': '501411', 'categoryname': '工作灯'},
        {'categoryid': '501412', 'categoryname': 'LED灯'},
        {'categoryid': '501413', 'categoryname': '荧光灯'},
        {'categoryid': '501417', 'categoryname': '景观灯'},
        {'categoryid': '501418', 'categoryname': '开关插座'},
        {'categoryid': '501419', 'categoryname': '地插'},
        {'categoryid': '501421', 'categoryname': '节能灯'},
        {'categoryid': '501422', 'categoryname': '室内灯具'},
        {'categoryid': '501423', 'categoryname': '其他灯/光源'},
        {'categoryid': '601010', 'categoryname': '安全帽'},
        {'categoryid': '601011', 'categoryname': '安全帽配件'},
        {'categoryid': '601012', 'categoryname': '防护帽'},
        {'categoryid': '601110', 'categoryname': '防护眼镜'},
        {'categoryid': '601112', 'categoryname': '防护面屏'},
        {'categoryid': '601210', 'categoryname': '耳塞'},
        {'categoryid': '601211', 'categoryname': '耳罩'},
        {'categoryid': '601212', 'categoryname': '耳塞分配器'},
        {'categoryid': '601310', 'categoryname': '防护口罩'},
        {'categoryid': '601311', 'categoryname': '防护面具'},
        {'categoryid': '601312', 'categoryname': '滤盒'},
        {'categoryid': '601313', 'categoryname': '滤棉及附件'},
        {'categoryid': '601410', 'categoryname': '一次性手套'},
        {'categoryid': '601411', 'categoryname': '通用手套'},
        {'categoryid': '601412', 'categoryname': '防割手套'},
        {'categoryid': '601413', 'categoryname': '防化手套'},
        {'categoryid': '601416', 'categoryname': '焊接手套'},
        {'categoryid': '601418', 'categoryname': '特殊用途手套'},
        {'categoryid': '601419', 'categoryname': '防冻手套'},
        {'categoryid': '601511', 'categoryname': '防化服'},
        {'categoryid': '601513', 'categoryname': '隔温防护服'},
        {'categoryid': '601514', 'categoryname': '工作服'},
        {'categoryid': '601516', 'categoryname': '围裙'},
        {'categoryid': '601517', 'categoryname': '雨衣'},
        {'categoryid': '601518', 'categoryname': '反光背心'},
        {'categoryid': '601519', 'categoryname': '其他'},
        {'categoryid': '601610', 'categoryname': '鞋套'},
        {'categoryid': '601611', 'categoryname': '安全鞋'},
        {'categoryid': '601612', 'categoryname': '安全靴'},
        {'categoryid': '601814', 'categoryname': '安全绳'},
        {'categoryid': '601815', 'categoryname': '安全钩'},
        {'categoryid': '601816', 'categoryname': '安全腰带'},
        {'categoryid': '601817', 'categoryname': '缓冲系绳'},
        {'categoryid': '601818', 'categoryname': '支架'},
        {'categoryid': '601819', 'categoryname': '缓冲装备'},
        {'categoryid': '601899', 'categoryname': '其他'},
        {'categoryid': '601915', 'categoryname': '其他救援设备'},
        {'categoryid': '101010', 'categoryname': '综合工具套装'},
        {'categoryid': '101011', 'categoryname': '工具托套装'},
        {'categoryid': '101014', 'categoryname': '电子电讯工具套装'},
        {'categoryid': '101110', 'categoryname': '工具箱'},
        {'categoryid': '101112', 'categoryname': '工具包'},
        {'categoryid': '101210', 'categoryname': '活动扳手'},
        {'categoryid': '101211', 'categoryname': '两用扳手'},
        {'categoryid': '101212', 'categoryname': '内六角扳手'},
        {'categoryid': '101213', 'categoryname': '扭力扳手'},
        {'categoryid': '101214', 'categoryname': '棘轮扳手'},
        {'categoryid': '101215', 'categoryname': '开口扳手'},
        {'categoryid': '101217', 'categoryname': '梅花扳手'},
        {'categoryid': '101219', 'categoryname': '套筒扳手'},
        {'categoryid': '101220', 'categoryname': '其他扳手'},
        {'categoryid': '101221', 'categoryname': '扳手组套'},
        {'categoryid': '101222', 'categoryname': '套筒'},
        {'categoryid': '101225', 'categoryname': '旋具套筒'},
        {'categoryid': '101223', 'categoryname': '套筒组套'},
        {'categoryid': '101224', 'categoryname': '套筒配件'},
        {'categoryid': '101310', 'categoryname': '一字螺丝批'},
        {'categoryid': '101311', 'categoryname': '十字螺丝批'},
        {'categoryid': '101319', 'categoryname': '六角螺丝批'},
        {'categoryid': '101318', 'categoryname': '花形螺丝批'},
        {'categoryid': '101320', 'categoryname': '螺帽螺丝批'},
        {'categoryid': '101312', 'categoryname': '棘轮螺丝批'},
        {'categoryid': '101322', 'categoryname': '微型螺丝批'},
        {'categoryid': '101313', 'categoryname': '其他螺丝批'},
        {'categoryid': '101314', 'categoryname': '螺丝批组套'},
        {'categoryid': '101315', 'categoryname': '旋具头、批咀'},
        {'categoryid': '101316', 'categoryname': '旋具头组套'},
        {'categoryid': '101410', 'categoryname': '尖嘴钳'},
        {'categoryid': '101411', 'categoryname': '斜嘴钳'},
        {'categoryid': '101421', 'categoryname': '弯嘴钳'},
        {'categoryid': '101412', 'categoryname': '钢丝钳'},
        {'categoryid': '101414', 'categoryname': '鲤鱼钳'},
        {'categoryid': '101415', 'categoryname': '水泵钳'},
        {'categoryid': '101416', 'categoryname': '卡簧钳/挡圈钳'},
        {'categoryid': '101417', 'categoryname': '断线钳'},
        {'categoryid': '101419', 'categoryname': '大力钳'},
        {'categoryid': '101424', 'categoryname': '台虎钳'},
        {'categoryid': '101427', 'categoryname': 'G形夹/C形夹'},
        {'categoryid': '101420', 'categoryname': '其他钳类'},
        {'categoryid': '101527', 'categoryname': '美工刀/割刀'},
        {'categoryid': '101528', 'categoryname': '雕刻刀'},
        {'categoryid': '101530', 'categoryname': '电工刀/剥线刀'},
        {'categoryid': '101511', 'categoryname': '航空剪'},
        {'categoryid': '101512', 'categoryname': '铁皮剪'},
        {'categoryid': '101532', 'categoryname': '通用剪'},
        {'categoryid': '101513', 'categoryname': '锯弓锯条'},
        {'categoryid': '101514', 'categoryname': '锉'},
        {'categoryid': '101515', 'categoryname': '开孔器'},
        {'categoryid': '101517', 'categoryname': '撬棍'},
        {'categoryid': '101533', 'categoryname': '冲/凿/铲'},
        {'categoryid': '101519', 'categoryname': '圆头锤'},
        {'categoryid': '101520', 'categoryname': '羊角锤'},
        {'categoryid': '101521', 'categoryname': '钳工锤'},
        {'categoryid': '101522', 'categoryname': '安装锤'},
        {'categoryid': '101523', 'categoryname': '防震橡皮锤'},
        {'categoryid': '101538', 'categoryname': '八角锤'},
        {'categoryid': '101525', 'categoryname': '其他敲击工具'},
        {'categoryid': '101526', 'categoryname': '其他切割工具'},
        {'categoryid': '101710', 'categoryname': '防静电手腕带'},
        {'categoryid': '101716', 'categoryname': '防静电钳子'},
        {'categoryid': '101712', 'categoryname': '镊子'},
        {'categoryid': '101713', 'categoryname': '测电笔'},
        {'categoryid': '101719', 'categoryname': '压线钳'},
        {'categoryid': '101720', 'categoryname': '剥线钳'},
        {'categoryid': '101721', 'categoryname': '电子钳'},
        {'categoryid': '101722', 'categoryname': '电工剪'},
        {'categoryid': '101723', 'categoryname': '线缆剪'},
        {'categoryid': '101726', 'categoryname': '绝缘钳'},
        {'categoryid': '101727', 'categoryname': '绝缘螺丝批'},
        {'categoryid': '101799', 'categoryname': '其他电工电子工具'},
        {'categoryid': '102510', 'categoryname': '管钳'},
        {'categoryid': '102511', 'categoryname': '切管工具'},
        {'categoryid': '102512', 'categoryname': '弯管器'},
        {'categoryid': '102610', 'categoryname': '电器维修工具'},
        {'categoryid': '102611', 'categoryname': '轮胎维修工具'},
        {'categoryid': '102612', 'categoryname': '润滑设备及工具'},
        {'categoryid': '102613', 'categoryname': '引擎维修工具'},
        {'categoryid': '102615', 'categoryname': '底盘维修工具'},
        {'categoryid': '102699', 'categoryname': '其他维修工具'},
        {'categoryid': '102710', 'categoryname': '园林剪'},
        {'categoryid': '102711', 'categoryname': '割草机'},
        {'categoryid': '102810', 'categoryname': '防爆扳手'},
        {'categoryid': '101814', 'categoryname': '拉铆枪'},
        {'categoryid': '101815', 'categoryname': '拉马'},
        {'categoryid': '101816', 'categoryname': '断丝取出器'},
        {'categoryid': '101817', 'categoryname': '拾捡工具'},
        {'categoryid': '101819', 'categoryname': '扎带工具'},
        {'categoryid': '101820', 'categoryname': '线槽工具'},
        {'categoryid': '101899', 'categoryname': '其他'},
        {'categoryid': '101910', 'categoryname': '电钻'},
        {'categoryid': '101911', 'categoryname': '冲击钻'},
        {'categoryid': '101915', 'categoryname': '直磨机'},
        {'categoryid': '101916', 'categoryname': '角磨机'},
        {'categoryid': '101913', 'categoryname': '电锤'},
        {'categoryid': '101914', 'categoryname': '电镐'},
        {'categoryid': '101919', 'categoryname': '切割机'},
        {'categoryid': '101924', 'categoryname': '电圆锯'},
        {'categoryid': '101925', 'categoryname': '斜切锯'},
        {'categoryid': '101926', 'categoryname': '往复锯/马刀锯'},
        {'categoryid': '101921', 'categoryname': '砂纸机/砂光机'},
        {'categoryid': '101922', 'categoryname': '砂轮机'},
        {'categoryid': '101931', 'categoryname': '热风枪'},
        {'categoryid': '101928', 'categoryname': '电刨/台刨'},
        {'categoryid': '101929', 'categoryname': '修边机/电木铣'},
        {'categoryid': '101912', 'categoryname': '电动螺丝刀/起子机'},
        {'categoryid': '101936', 'categoryname': '磁座钻'},
        {'categoryid': '101923', 'categoryname': '电动扳手'},
        {'categoryid': '101917', 'categoryname': '电剪/电冲剪'},
        {'categoryid': '101932', 'categoryname': '热胶枪'},
        {'categoryid': '101920', 'categoryname': '其他电动工具'},
        {'categoryid': '102014', 'categoryname': '吹气枪/吹尘枪'},
        {'categoryid': '102016', 'categoryname': '气动钉枪'},
        {'categoryid': '102113', 'categoryname': '钻头'},
        {'categoryid': '102114', 'categoryname': '锯片'},
        {'categoryid': '102116', 'categoryname': '风动套筒'},
        {'categoryid': '102199', 'categoryname': '其他动力工具附件'},
        {'categoryid': '102412', 'categoryname': '硅胶枪'},
        {'categoryid': '102415', 'categoryname': '刮刀'},
        {'categoryid': '102417', 'categoryname': '铲刀'},
        {'categoryid': '201010', 'categoryname': '直尺'},
        {'categoryid': '201011', 'categoryname': '卷尺'},
        {'categoryid': '201012', 'categoryname': '水平仪'},
        {'categoryid': '201013', 'categoryname': '角尺'},
        {'categoryid': '201015', 'categoryname': '卡尺'},
        {'categoryid': '201016', 'categoryname': '千分尺'},
        {'categoryid': '201018', 'categoryname': '高度尺'},
        {'categoryid': '201019', 'categoryname': '塞尺'},
        {'categoryid': '201020', 'categoryname': '卡规'},
        {'categoryid': '201022', 'categoryname': '百分表'},
        {'categoryid': '201023', 'categoryname': '千分表'},
        {'categoryid': '201024', 'categoryname': '磁性表座'},
        {'categoryid': '201027', 'categoryname': '量块'},
        {'categoryid': '201099', 'categoryname': '其他'},
        {'categoryid': '201111', 'categoryname': '电工测量仪表'},
        {'categoryid': '201112', 'categoryname': '电子测量仪表'},
        {'categoryid': '201113', 'categoryname': '温度、湿度测量仪表'},
        {'categoryid': '201114', 'categoryname': '环境测量仪表'},
        {'categoryid': '201116', 'categoryname': '形状测量仪'},
        {'categoryid': '201117', 'categoryname': '气检仪及相关产品'},
        {'categoryid': '301318', 'categoryname': '工业百洁布'},
        {'categoryid': '301317', 'categoryname': '砂纸、砂布、砂带'},
        {'categoryid': '301321', 'categoryname': '百叶轮'},
        {'categoryid': '301312', 'categoryname': '打磨片'},
        {'categoryid': '301313', 'categoryname': '切割片'},
        {'categoryid': '301319', 'categoryname': '抛光研磨剂'},
        {'categoryid': '301399', 'categoryname': '其他磨具磨料'},
        {'categoryid': '301414', 'categoryname': '胶粘剂'},
        {'categoryid': '301411', 'categoryname': '防锈产品'},
        {'categoryid': '301412', 'categoryname': '润滑油'},
        {'categoryid': '302210', 'categoryname': 'VHB胶带'},
        {'categoryid': '302211', 'categoryname': '纤维胶带'},
        {'categoryid': '302212', 'categoryname': '双面胶带'},
        {'categoryid': '302213', 'categoryname': '遮蔽胶带'},
        {'categoryid': '302215', 'categoryname': '封箱胶带'},
        {'categoryid': '302216', 'categoryname': '警示胶带'},
        {'categoryid': '302217', 'categoryname': '布基胶带'},
        {'categoryid': '302218', 'categoryname': '铝箔胶带'},
        {'categoryid': '302219', 'categoryname': '胶带切割器'},
        {'categoryid': '302220', 'categoryname': '其他胶带'},
        {'categoryid': '302610', 'categoryname': '普通高速钢麻花钻'},
        {'categoryid': '301510', 'categoryname': '丝锥扳手'},
        {'categoryid': '301513', 'categoryname': '直槽丝锥'},
        {'categoryid': '301518', 'categoryname': '手用丝锥'},
        {'categoryid': '301599', 'categoryname': '其他'},
        {'categoryid': '302112', 'categoryname': '强力刀柄'},
        {'categoryid': '302510', 'categoryname': 'ER筒夹'},
        {'categoryid': '302511', 'categoryname': '强力筒夹'},
        {'categoryid': '302515', 'categoryname': '拉钉'},
        {'categoryid': '301210', 'categoryname': '电烙铁'},
        {'categoryid': '301212', 'categoryname': '弧焊设备'},
        {'categoryid': '301213', 'categoryname': '焊接附件'},
        {'categoryid': '301214', 'categoryname': '焊材'},
        {'categoryid': '402010', 'categoryname': '深沟球轴承'},
        {'categoryid': '402410', 'categoryname': '空气过滤器'},
        {'categoryid': '402412', 'categoryname': '调压阀'},
        {'categoryid': '402413', 'categoryname': '过滤减压阀'},
        {'categoryid': '402414', 'categoryname': '气源处理组合'},
        {'categoryid': '402415', 'categoryname': '微雾分离器'},
        {'categoryid': '402416', 'categoryname': '油雾器'},
        {'categoryid': '402417', 'categoryname': '排水器'},
        {'categoryid': '402499', 'categoryname': '其他气源处理元件'},
        {'categoryid': '402510', 'categoryname': '压力开关'},
        {'categoryid': '402511', 'categoryname': '流量开关'},
        {'categoryid': '402610', 'categoryname': '通用气管'},
        {'categoryid': '402611', 'categoryname': '螺旋气管'},
        {'categoryid': '402710', 'categoryname': '标准型气缸'},
        {'categoryid': '402711', 'categoryname': '无杆气缸'},
        {'categoryid': '402712', 'categoryname': '带导向气缸'},
        {'categoryid': '402713', 'categoryname': '摆动气缸/回转气缸'},
        {'categoryid': '402714', 'categoryname': '止动气缸'},
        {'categoryid': '402715', 'categoryname': '紧凑型气缸'},
        {'categoryid': '402716', 'categoryname': '气动滑台'},
        {'categoryid': '402717', 'categoryname': '夹紧气缸'},
        {'categoryid': '402720', 'categoryname': '气爪'},
        {'categoryid': '402721', 'categoryname': '磁性开关'},
        {'categoryid': '402722', 'categoryname': '气缸附件'},
        {'categoryid': '402810', 'categoryname': '气控阀'},
        {'categoryid': '402811', 'categoryname': '电磁阀'},
        {'categoryid': '402812', 'categoryname': '机控阀/手控阀'},
        {'categoryid': '402813', 'categoryname': '电气比例阀'},
        {'categoryid': '402814', 'categoryname': '增压阀'},
        {'categoryid': '402815', 'categoryname': '流体控制阀'},
        {'categoryid': '402816', 'categoryname': '精密调压阀'},
        {'categoryid': '402817', 'categoryname': '调速阀'},
        {'categoryid': '402818', 'categoryname': '快速排气阀'},
        {'categoryid': '402819', 'categoryname': '单向阀'},
        {'categoryid': '402820', 'categoryname': '阀附件'},
        {'categoryid': '402899', 'categoryname': '其他阀'},
        {'categoryid': '402910', 'categoryname': '真空发生器'},
        {'categoryid': '402911', 'categoryname': '真空过滤器'},
        {'categoryid': '402912', 'categoryname': '真空吸盘'},
        {'categoryid': '402913', 'categoryname': '真空压力表'},
        {'categoryid': '402999', 'categoryname': '真空用其他元件'},
        {'categoryid': '403010', 'categoryname': '消声器'},
        {'categoryid': '403011', 'categoryname': '液压缓冲器'},
        {'categoryid': '403013', 'categoryname': '排气洁净器'},
        {'categoryid': '403014', 'categoryname': '压力表'},
        {'categoryid': '403099', 'categoryname': '其他'},
        {'categoryid': '403110', 'categoryname': '通用管接头'},
        {'categoryid': '403112', 'categoryname': '微型管接头'},
        {'categoryid': '403114', 'categoryname': '带单向阀的快插接头'},
        {'categoryid': '403115', 'categoryname': '特殊环境用管接头'},
        {'categoryid': '701010', 'categoryname': '办公用纸'},
        {'categoryid': '701011', 'categoryname': '办公文具'},
        {'categoryid': '701012', 'categoryname': '办公胶带'},
        {'categoryid': '701013', 'categoryname': '黑板、写字板'},
        {'categoryid': '701014', 'categoryname': '计算器'},
        {'categoryid': '701110', 'categoryname': '打印机、复印机及耗材'},
        {'categoryid': '701119', 'categoryname': '装订/封装机'},
        {'categoryid': '701212', 'categoryname': '隔板、架子'},
        {'categoryid': '701213', 'categoryname': '箱柜'},
        {'categoryid': '701312', 'categoryname': '梯子'},
        {'categoryid': '701313', 'categoryname': '保鲜袋、保鲜膜'},
        {'categoryid': '701317', 'categoryname': '小家电'},
        {'categoryid': '701510', 'categoryname': '擦拭纸、布'},
        {'categoryid': '701511', 'categoryname': '抹布'},
        {'categoryid': '701512', 'categoryname': '洗涤剂'},
        {'categoryid': '701515', 'categoryname': '吸附材料'},
        {'categoryid': '701610', 'categoryname': '刷子'},
        {'categoryid': '701621', 'categoryname': '百洁布'},
        {'categoryid': '701611', 'categoryname': '拖把'},
        {'categoryid': '701612', 'categoryname': '扫帚、簸箕'},
        {'categoryid': '701613', 'categoryname': '桶、垃圾桶'},
        {'categoryid': '701615', 'categoryname': '钢丝球'},
        {'categoryid': '701619', 'categoryname': '其他清洁工具'},
        {'categoryid': '701620', 'categoryname': '清洁工具附件'},
        {'categoryid': '701712', 'categoryname': '吸尘器'},
        {'categoryid': '701910', 'categoryname': '风扇'},
        {'categoryid': '701911', 'categoryname': '风机'},
        {'categoryid': '702112', 'categoryname': '食品、化工软管'}
    ]
    requests.adapters.DEFAULT_RETRIES = 5
    for item in categorys[:3]:
        url = 'http://www.vipmro.com/search?categoryId={0}'.format(item['categoryid'])
        name = item['categoryname'] + '.txt'
        item_product = getinfo(url, name)
        with open(name, 'w', encoding='utf-8') as f:
            f.writelines(item_product)
            print(item['categoryname'])
